[package]
name = "panic-example-test"
description = "Tests for the text produced by using descriptive-unwrap."
publish = false
edition = "2021"

[[bin]]
name = "panic-example-test"
test = false # no unit tests

[dependencies]
descriptive-unwrap = { path = "../" }

[dev-dependencies]
trycmd = { version = "1.0.0" }